apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: internal-periodic-metrics-reporter
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: internal-periodic-metrics-reporter-secrets
    - secret: influxdb-credentials
  image: {{version}}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 5
  readiness:
    path: /internal/isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  ingresses:
    - "https://internal-periodic-metrics-reporter-gcp.nais.oera.no"
  webproxy: true
  resources:
    limits:
      cpu: "3"
      memory: 4500Mi
    requests:
      cpu: "1"
      memory: 3840Mi
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: kafka-schema-registry.nais.adeo.no
