apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: internal-periodic-metrics-reporter
  namespace: {{namespace}}
  labels:
    team: personbruker
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 5
  readiness:
    path: /internal/isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  ingresses:
  {{#each ingresses}}
    - "{{this}}"
  {{/each}}
  vault:
    enabled: true
    paths:
      - kvPath: /kv/{{cluster}}/sbs/internal-periodic-metrics-reporter/{{namespace}}
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /serviceuser/data/{{environment}}/srvdittnav-p-metrics
        mountPath: /secret/serviceuser
  resources:
    limits:
      cpu: "3"
      memory: 4800Mi
    requests:
      cpu: "1"
      memory: 4096Mi
  kafka:
    pool: {{kafkapool}}
